# Generated by Django 4.1.7 on 2023-02-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_task_options_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'priority']},
        ),
    ]
