# Generated by Django 4.1.7 on 2023-02-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-priority']},
        ),
    ]
