# Generated by Django 4.1.7 on 2023-03-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['username']},
        ),
    ]
